// See https://svelte.dev/docs/kit/types#app.d.ts
// `Env` below is generated by `yarn cf-typegen` (wrangler types) into worker-configuration.d.ts
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
		interface Platform {
			env: Env;
			cf: CfProperties;
			ctx: ExecutionContext;
		}
	}
}

export {};
